### ISSUE TITLE
Can you help me or tutor me in UBCx capstone project.

### ISSUE THREAD

**Issue by nileshdattatraykedare** [braxtonhall/secretdj#2]
Hi @braxtonhall Braxton I am Neel I have completed all courses under micromaster but capstone project i am struggling since very long time. Can you please guide me or tutor me to complete it.

**Comment by braxtonhall** [comment]
Hi there @nileshdattatraykedare .

This isn't the way I'd like to be contacted! I think moving forward, I will be ignoring messages regarding the UBCx Software Engineering Capstone Project if not sent via _your_ SECapstone repository, the edx discussion board, or the Slack workspace found on the discussion board.

If I miss a message from one of those three avenues, feel free to send as many as you need until I get back to you.

Thanks!
Braxton.
